language: dart
dist: xenial
addons:
  apt:
    packages:
    - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov
script:
  - cd FARTS
  - ../flutter/bin/flutter test --coverage
after_success:
  - coveralls-lcov --repo-token $COVERALLS_TOKEN coverage/lcov.info
cache:
  directories:
  - $HOME/.pub-cache